### ISSUE TITLE
Add credential manager storing setup

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/arcCommander-docs#4]
In the section [sharing your arc](https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/implementation/QuickStart_arcCommander.html#sharing-your-arc), prior to running the `remote token get` command, it might be necessary to setup git credential storing:

Windows:
`git config --global credential.helper cache`
or
`git config --global credential.helper store`

Mac:
`git config --global credential.helper osxkeychain`

**Comment by Brilator** [comment]
Move issue to [knowledge base](https://github.com/nfdi4plants/nfdi4plants.knowledgebase) ;)
